"""Quorum Core Package.

Pure domain models, ranking, fingerprinting, policy, suppression, and configuration.
Strictly zero framework or I/O imports.
"""
from quorum_core.models import (
    EvidenceClass,
    SourceType,
    Severity,
    FindingCategory,
    FindingStatus,
    VerificationVerdict,
    TriageMode,
    Evidence,
    Finding,
    Verification,
    RepoConfig,
    Policy,
    Suppression,
    Learning,
    UsageRecord,
    DiffHunk,
    DiffFile,
    DiffSummary,
    PRMeta,
    CheckResult,
    TriageDecision,
    AnalyzerResult,
    RetrievedChunk,
    RetrievedContext,
    PostedComment,
    ReviewSummary,
)
from quorum_core.fingerprint import compute_fingerprint, normalize_snippet, normalize_claim
from quorum_core.ranking import (
    SEVERITY_WEIGHTS,
    calculate_rank_score,
    is_eligible_for_publication,
    apply_comment_budget,
)
from quorum_core.policy import evaluate_policy, check_sensitive_paths, PolicyEvaluationResult
from quorum_core.suppression import evaluate_suppressions
from quorum_core.config_merge import merge_config, validate_config_dict
from quorum_core.errors import (
    ProblemDetail,
    QuorumDomainError,
    ConfigError,
    PolicyViolationError,
    VerificationError,
    AuthenticationError,
    AuthorizationError,
    NotFoundError,
)

__all__ = [
    "EvidenceClass",
    "SourceType",
    "Severity",
    "FindingCategory",
    "FindingStatus",
    "VerificationVerdict",
    "TriageMode",
    "Evidence",
    "Finding",
    "Verification",
    "RepoConfig",
    "Policy",
    "Suppression",
    "Learning",
    "UsageRecord",
    "DiffHunk",
    "DiffFile",
    "DiffSummary",
    "PRMeta",
    "CheckResult",
    "TriageDecision",
    "AnalyzerResult",
    "RetrievedChunk",
    "RetrievedContext",
    "PostedComment",
    "ReviewSummary",
    "compute_fingerprint",
    "normalize_snippet",
    "normalize_claim",
    "SEVERITY_WEIGHTS",
    "calculate_rank_score",
    "is_eligible_for_publication",
    "apply_comment_budget",
    "evaluate_policy",
    "check_sensitive_paths",
    "PolicyEvaluationResult",
    "evaluate_suppressions",
    "merge_config",
    "validate_config_dict",
    "ProblemDetail",
    "QuorumDomainError",
    "ConfigError",
    "PolicyViolationError",
    "VerificationError",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
]
